image: alpine/latest
packages:
  - openjdk8
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~luketurner/factor
secrets:
  # ~/netlify_config -- expected to have:
  #   NETLIFY_SITE_ID
  #   export NETLIFY_AUTH_TOKEN
  - 0b000959-802e-444a-8f76-07b005113647
tasks:
  - install-node-modules: |
      cd factor
      npm i --no-progress
      npm i netlify-cli --quiet --no-progress
  - build-js: |
      cd factor
      npm run build
      rm public/js/manifest.edn
  - run-tests: |
      cd factor
      npm run test
  - deploy: |
      cd factor
      set -e
      if [ "$(git rev-parse origin/master)" == "$(git rev-parse HEAD)" ]; then
        echo "deploying..."
        set +x
        source ~/netlify_config
        node_modules/.bin/netlify deploy --site="$NETLIFY_SITE_ID" --dir=public --prod >/dev/null 2>&1
        set -x
      else
        echo "skipping deployment for branch"
      fi

