image: alpine/latest
packages:
  - openjdk8
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~luketurner/factor
secrets:
  # ~/netlify_config -- expected to have:
  #   NETLIFY_SITE_ID
  #   export NETLIFY_AUTH_TOKEN
  - 18869b88-8dd8-45e8-b13b-b34c695a1e3b
tasks:
  - install-node-modules: |
      cd factor
      npm i --no-progress
      npm i netlify-cli --quiet --no-progress
  - build-js: |
      cd factor
      npm run build
      rm public/js/manifest.edn
  - deploy: |
      source ~/netlify_config
      cd factor
      node_modules/.bin/netlify deploy --site="$NETLIFY_SITE_ID" --dir=public --prod
  